feat: implementing banking_api
kmsskelly/banking_api pull request #1
Opened 2021-04-15 23:20 UTC by kmsskelly

2021-04-20 01:14 UTC, ramondelemos requested changes
Além dos demais pontos que levantei configure o [credo](https://hexdocs.pm/credo/overview.html) no projeto, use a flag --strict e faça as mudanças sugeridas.

2021-04-20 01:14 UTC, ramondelemos commented on apps/banking_api/.gitignore
> +# The directory Mix will write compiled artifacts to.
Esse arquivo não é necessário uma vez que temos um na raís do projeto.

2021-04-20 01:14 UTC, ramondelemos commented on apps/banking_api/README.md
> +**TODO: Add description**
Esse arquivo não é necessário, a não ser que tem alguma observação pontual por app da aplicação.

2021-04-20 01:14 UTC, ramondelemos commented on apps/banking_api/priv/repo/migrations/20210415132403_create_users_table.exs
> +      add :balance, :integer
O que acontece se tivermos um usuário com saldo maior ou igual a 2147483648?

2021-04-20 01:14 UTC, ramondelemos commented on apps/banking_api/test/accounts/operation_test.exs
> +      assert {:ok, %User{email: "fulano@mail.com", name: "Fulano", id: _, balance: _, password: "123456"}} = Operation.call(params, :withdraw)
Por quê não validar o saldo e id do usuário?

2021-04-20 01:14 UTC, ramondelemos commented on apps/banking_api/test/accounts/operation_test.exs
> +      params = %{"id" => user.id, "value" => 5000}
Essa parte do código está se repetindo, imagine o sistema crescendo para mais uns 100 casos de teste. Dê uma pesquisada sobre o princípio de software [DRY](https://www.wikiwand.com/en/Don%27t_repeat_yourself) e pense em como refatorar essa parte.

2021-04-20 01:14 UTC, ramondelemos commented on apps/banking_api/test/accounts/transaction_test.exs
> +      assert {:error, :not_enough_funds} = Transaction.call(params)
É garantido que as contas de fato não foram alteradas no banco de dados?

2021-04-20 01:14 UTC, ramondelemos commented on apps/banking_api/test/support/data_case.ex
> +  def errors_on(changeset) do
Interessante abordagem para reutilização de código.

2021-04-20 01:14 UTC, ramondelemos commented on README.md
> +Now you can visit [`localhost:4000`](http://localhost:4000) from your browser.
Umas das mais frequêntes tarefas que realizamos é revisar e executar código dos nossos pares, se um outro desenvolverdor tentar executar seu código só funciona se ele estiver com a mesma versão ou superir do elixir que você. Uma das ferramentas que utilizamos para contornar isso é o docker e/ou [asdf](https://asdf-vm.com). O asdf nos permite configurar o ambiente de desenvolvimento através do arquivo [.tool-versions
](https://asdf-vm.com/#/core-configuration?id=tool-versions), uma vez configurado qualquer ambiente pode ter suas dependências instaladas executando o comando `asdf install`. E é sempre bom que isso esteja de forma explícita descrita no README.md do projeto.

2021-04-20 01:14 UTC, ramondelemos commented on README.md
> +  * Create and migrate your database with `mix ecto.setup`
Não reflete o que está configurado na aplicação:

```bash
 > mix ecto.setup
** (Mix) The task "ecto.setup" could not be found. Did you mean "ecto.dump"?

> mix setup
The database for BankingApi.Repo has been created

21:17:26.263 [info]  == Running 20210415132403 BankingApi.Repo.Migrations.CreateUsersTable.change/0 forward

21:17:26.265 [info]  create table users

21:17:26.269 [info]  create index users_email_index

21:17:26.271 [info]  == Migrated 20210415132403 in 0.0s
```

2021-04-20 01:14 UTC, ramondelemos commented on apps/banking_api/lib/banking_api/accounts/transaction.ex
> +        Deposit.call(params_deposit)
Se essa operação falhar teremos retirado o dinheiro da conta de origem sem depositar em algum lugar. Podemos contornar esse problema tornando toda a operação de transferência atômica [ACID](https://www.wikiwand.com/en/ACID).

2021-04-20 01:14 UTC, ramondelemos commented on apps/banking_api_web/.formatter.exs
> +[
Esse arquivo é redundante uma vez que temos o mesmo na raíz do projeto.

2021-04-20 01:14 UTC, ramondelemos commented on apps/banking_api_web/.gitignore
> +# The directory Mix will write compiled artifacts to.
Esse arquivo é redundante uma vez que temos o mesmo na raíz do projeto.

2021-04-20 01:14 UTC, ramondelemos commented on apps/banking_api_web/test/banking_api_web/controllers/accounts_controller_test.exs
> +               "balance" => _balance,
Faça a asserção de que o valor foi modificado para o esperado. Sempre tenha controle das entradas e saídas em seus testes, e quando não for possível esse controle torne explícito utilizando [mocks](https://elixirschool.com/en/lessons/basics/testing/#test-mocks).

2021-04-20 12:44 UTC, kmsskelly commented on apps/banking_api/test/accounts/operation_test.exs
> +      assert {:ok, %User{email: "fulano@mail.com", name: "Fulano", id: _, balance: _, password: "123456"}} = Operation.call(params, :withdraw)
Você diz em outra etapa, sem ser aqui no teste?

2021-04-20 18:39 UTC, JVZELLER commented on apps/banking_api/lib/banking_api/accounts/deposit.ex
> +  end
```suggestion
  def call(params), do: Operation.call(params, :deposit)
```
Seguindo as sugestões de formatação do credo para [Single pipe](https://hexdocs.pm/credo/Credo.Check.Readability.SinglePipe.html#content).

Deixar a declaração em úma única linha é mais frescura mesmo, mas o single pipe vale a pena.

2021-04-20 18:39 UTC, JVZELLER commented on apps/banking_api/lib/banking_api/accounts/operation.ex
> +  call function receives the user's account id, the value and the type of the operation.
```suggestion
  `call/2` function receives the user's account id, the value and the type of the operation.
```

2021-04-20 18:39 UTC, JVZELLER commented on apps/banking_api/lib/banking_api/accounts/operation.ex
> +    |> Multi.run(:update_user, fn repo, %{get_user: user} ->
Aqui dá para usar `Multi.update/4` também.

Docs: https://hexdocs.pm/ecto/Ecto.Multi.html#update/4

2021-04-20 18:39 UTC, JVZELLER commented on apps/banking_api/lib/banking_api/user.ex
> +    |> cast(params, [:name, :email, :password, :balance])
```suggestion
    |> cast(params, __schema__(:fields))
```
Aqui podemos simplificar com essa função do `Ecto.Schema`. Vale lembrar que ela retorna uma lista de campos **não** virtuais (campos do tipo `field(:name, :string, virtual: true)` não seriam retornados), mas como aqui não temos nenhum, não precisamos nos preocupar com isso.

Docs: https://hexdocs.pm/ecto/Ecto.Schema.html#module-reflection

2021-04-20 18:39 UTC, JVZELLER commented on apps/banking_api/lib/banking_api/user.ex
> +    |> check_constraint(:balance, name: :balance_must_be_positive_or_zero)
Não sei se precisamos ir no banco validar essa constraint. Se validarmos no próprio changeset com `|> validate_number(:balance, greater_than_or_equal_to: 0)` antes de inserir ou atualizar um registro acho que já seria válido.
A constraint, no nosso cenário, serviria como proteção no caso de algum update que vá direto no banco, evitando que alguém torne um balance negativo com alguma query de update errada ou algo do tipo que não passe por um changeset antes.

2021-04-21 19:12 UTC, ramondelemos requested changes

2021-04-21 19:12 UTC, ramondelemos commented on apps/banking_api/lib/banking_api/accounts/transaction.ex
> +    end)
Não é necessário o uso do Multi.merge aqui.

```suggestion
    |> Multi.run(:get_to_user, fn _repo, _changes ->
      get_user(to_id)
    end)
    |> Multi.run(:update_to_user, fn repo, %{get_to_user: user} ->
      params = %{balance: user.balance + value}

      params
      |> User.changeset(user)
      |> repo.update()
    end)
```

2021-04-21 19:12 UTC, ramondelemos commented on apps/banking_api/test/accounts/transaction_test.exs
> +      assert {:error, :user_not_found} = Transaction.call(params)
Qual dos usuários não existe? Seria interessante tornar claro quais dos usuários não existem, se o de origem ou o de destino.

2021-04-21 19:12 UTC, ramondelemos commented on apps/banking_api_web/test/banking_api_web/controllers/accounts_controller_test.exs
> +      assert %{
Além da asserção do retorno do controller, valide ser os resultados foram persistidos no banco de dados.

2021-04-21 19:12 UTC, ramondelemos commented on apps/banking_api_web/test/banking_api_web/controllers/accounts_controller_test.exs
> +  describe "POST api/users/transaction" do
Faltou testar o caso de não ter dinheiro suficiente na origem.

2021-04-21 19:12 UTC, ramondelemos commented on apps/banking_api/.formatter.exs
> +]
Para que as formatações se extendam para o projeto web o ideal seria que esse arquivo fosse movido para a raíz do projeto, colocando o diretório `/apps` em `subdirectories:`. Outro ponto importante é que para que os padrões de formatação das dependências que utilizamos sejam aplicadas podemos também configurá-las nesse arquivo em `import_deps`. Todos os demais arquivos `.formatter.exs` podem ser removidos. [mix format](https://hexdocs.pm/mix/master/Mix.Tasks.Format.html)

```suggestion
[
  import_deps: [:phoenix, :plug, :ecto, :ecto_sql],
  inputs: ["mix.exs", "{config,lib,priv,test}/**/*.{ex,exs}"],
  subdirectories: ["apps/*"]
]
```

2021-04-21 19:12 UTC, ramondelemos commented on .tool-versions
> +erlang 23.2.7
É recomendado sempre ter uma quebra de linha ao final dos arquivos.
```suggestion
erlang 23.2.7

```

2021-04-21 19:12 UTC, ramondelemos commented on docker-compose.yaml
> +      - 5432:5432
Aqui também:
```suggestion
      - 5432:5432
      
```

2021-04-21 19:12 UTC, ramondelemos commented on docker-compose.yaml
> +      POSTGRES_PASSWORD: postgres
É uma boa prática trocar o usuário e senha default do postgresql, isso evita mascarar problemas no setup da aplicação.

```suggestion
      POSTGRES_USER: banking_api_user
      POSTGRES_PASSWORD: banking_api_pass
```

2021-04-21 19:12 UTC, ramondelemos commented on apps/banking_api/mix.exs
> +      {:credo, "~> 1.4", only: [:dev, :test], runtime: false}
Por ser uma dependência só do ambiente de desenvolvimento e se extender para todos os apps o credo pode ser movido para o arquivo mix.exs na raíz do umbrella.

2021-04-21 19:12 UTC, ramondelemos commented on apps/banking_api/priv/repo/migrations/.formatter.exs
> +[
Essa configuração pode ser movida para o arquivo na raíz do projeto.

2021-04-22 20:06 UTC, ramondelemos approved these changes
Nice!

Eu deixo para você mais dois desafios que eu acho que valem o esforço. Isso não é uma prioridade, mas eu acho que vai te ajudar a entender várias etapas do que temos nos projetos hoje. 

- Configure uma ferramenta de CI/CD e garanta que a cada commit sejam executados:
  - Validação da formatação
  - Validação do credo
  - Todos os testes passando com sucesso
- Configure o build de uma imagem docker com o release do projeto utilizando
  - Utilize o distillery para montar a release
  - Adicionar etapa de build ao pipeline de CI/CD

**Não precisa fazer o deploy, só executar o build**

Pode escolher qualquer uma das ferramentas abaixo:

- Circle CI
- Trevis CI
- GitHub Actions

2021-04-22 20:06 UTC, ramondelemos commented on apps/banking_api/lib/banking_api/accounts/transaction.ex
> +        {:ok, TransactionsResponse.build(from_id, to_id)}
Aqui você introduz um problema de corrida que pode ser difícil de depurar, como a transação já foi commitada o essa consulta pode retornar o resultado de outra operação concorrente e confundir quem executá-la.

2021-04-22 20:06 UTC, ramondelemos commented on apps/banking_api/lib/banking_api/accounts/transactions_response.ex
> +    from_user = get_user(from_id)
Em questões de performance está adicionando mais duas requisições ao banco de dados.

2021-04-22 20:06 UTC, ramondelemos commented on apps/banking_api_web/test/banking_api_web/controllers/accounts_controller_test.exs
> +      response = Repo.transaction(fn -> Enum.to_list(stream) end)
Nem precisa abrir uma transação aqui.

2021-04-22 20:50 UTC, kmsskelly commented on apps/banking_api/lib/banking_api/accounts/transaction.ex
> +        {:ok, TransactionsResponse.build(from_id, to_id)}
Como resolver isso, então?

2021-04-22 20:51 UTC, kmsskelly commented on apps/banking_api/lib/banking_api/accounts/transactions_response.ex
> +    from_user = get_user(from_id)
Qual seria outra forma de fazer?

2021-04-22 21:23 UTC, ramondelemos commented on apps/banking_api/lib/banking_api/accounts/transaction.ex
> +        {:ok, TransactionsResponse.build(from_id, to_id)}
Você pode retornar os registros que já estão no resultado.

```elixir
    |> Repo.transaction()
    |> case do
      {:ok, %{update_to_user: to_user, update_from_user: from_user}} ->
        {:ok, %TransactionsResponse{to_user: to_user, from_user: from_user}
```

2021-04-26 13:34 UTC, merged